version: '2'

services:
  prometheus:
    image: prometheus:v1
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"

grafana:
    image: grafana
    container_name: grafana
    volumes:
      - grafana_bkp:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Sahaj@123
    restart: unless-stopped
    expose:
      - "3000:3000"
      
alerting:
    image: quay.io/prometheus/alertmanager
    expose:
      - "9093:9093"
    volumes:
      - alert.rules.yml:/etc/prometheus/alert.rules.yml
      - alertmanager.yml:/etc/alertmanager/alertmanager.yml
